### ISSUE TITLE
inception get osc_percent 查看进度报错：ERROR 2013 (HY000): Lost connection to MySQL server during query

### ISSUE THREAD

**Issue by sona-yuan** [hanchuanchuan/goInception#316]
**描述**
inception get osc_percent 查看进度报错：ERROR 2013 (HY000): Lost connection to MySQL server during query

level=error msg="lastCmd inception get osc_percent '*9E7D9F0C8E27C41655C1FF248E0D13A75E18EBBE', runtime error: invalid memory address or nil pointer dereference, goroutine 15220 [running]:\ngithub.com/hanchuanchuan/goInception/server.(*clientConn).Run.func1(0xc00923bba0, 0xc0000e1dae)\n\t/Users/hanchuanchuan/coding/github.com/hanchuanchuan/goInception/server/conn.go:420 +0x105\npanic(0x1588460, 0x294f2b0)\n\t/usr/local/go/src/runtime/panic.go:969 +0x166\nsync.(*RWMutex).RLock(...)\n\t/usr/local/go/src/sync/rwmutex.go:48\ngithub.com/hanchuanchuan/goInception/session.(*session).executeLocalShowOscProcesslist(0xc007112000, 0xc00e10d590, 0xc0000e1450, 0x1, 0x1, 0xc00de578f8, 0x1)\n\t/Users/hanchuanchuan/coding/github.com/hanchuanchuan/goInception/session/session_inception.go:5953 +0x614\ngithub.com/hanchuanchuan/goInception/session.(*session).processCommand(0xc007112000, 0x1a47260, 0xc00dd64240, 0x1a4c7a0, 0xc00e10d590, 0xc0001417c1, 0x45, 0x17beecc, 0xf, 0xc00de94bd0, ...)\n\t/Users/hanchuanchuan/coding/github.com/hanchuanchuan/goInception/session/session_inception.go:661 +0x1112\ngithub.com/hanchuanchuan/goInception/session.(*session).executeInc(0xc007112000, 0x1a47260, 0xc00dd64240, 0xc0001417c1, 0x45, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/Users/hanchuanchuan/coding/github.com/hanchuanchuan/goInception/session/session_inception.go:379 +0x1de3\ngithub.com/hanchuanchuan/goInception/session.(*session).ExecuteInc(0xc007112000, 0x1a47260, 0xc00dd64240, 0xc0001417c1, 0x45, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/Users/hanchuanchuan/coding/github.com/hanchuanchuan/goInception/session/session_inception.go:122 +0x1c8\ngithub.com/hanchuanchuan/goInception/server.(*TiDBContext).Execute(0xc00dd5b860, 0x1a47260, 0xc00dd64240, 0xc0001417c1, 0x45, 0x0, 0x0, 0x0, 0x4a, 0xc006d20a58)\n\t/Users/hanchuanchuan/coding/github.com/hanchuanchuan/goInception/server/driver_tidb.go:259 +0x7c\ngithub.com/hanchuanchuan/goInception/server.(*clientConn).handleQuery(0xc00923bba0, 0x1a47260, 0xc00dd64240, 0xc0001417c1, 0x45, 0x0, 0x0)\n\t/Users/hanchuanchuan/coding/github.com/hanchuanchuan/goInception/server/conn.go:880 +0xae\ngithub.com/hanchuanchuan/goInception/server.(*clientConn).dispatch(0xc00923bba0, 0xc0001417c1, 0x46, 0x46, 0x0, 0x0)\n\t/Users/hanchuanchuan/coding/github.com/hanchuanchuan/goInception/server/conn.go:632 +0x6e7\ngithub.com/hanchuanchuan/goInception/server.(*clientConn).Run(0xc00923bba0)\n\t/Users/hanchuanchuan/coding/github.com/hanchuanchuan/goInception/server/conn.go:465 +0x161\ngithub.com/hanchuanchuan/goInception/server.(*Server).onConn(0xc000290ee0, 0x1a5afe0, 0xc006d80f90)\n\t/Users/hanchuanchuan/coding/github.com/hanchuanchuan/goInception/server/server.go:327 +0x21d\ncreated by github.com/hanchuanchuan/goInception/server.(*Server).Run\n\t/Users/hanchuanchuan/coding/github.com/hanchuanchuan/goInception/server/server.go:272 +0x3f8\n" file=conn.go func=func1 line=422

**重现**
gh-ost执行alter之后，执行inception get osc_percent  报错，gh-ost执行完再执行inception get osc_percent  就没有报错了

**环境**
 - 数据库: [mysql]
 - 版本: [例如 5.7.31]

**参数**
可能与问题相关的设置参数

**Comment by sona-yuan** [comment]
https://github.com/hanchuanchuan/goInception/issues/309

**Comment by sona-yuan** [comment]
已解决
