### ISSUE TITLE
不支持查询分区表

### ISSUE THREAD

**Issue by viper-sina-info** [hanchuanchuan/goInception#612]
**描述**
查询分区表的时候报错？

**重现**

- 执行
`select order_no from user_wallet_log partition(p10);`

- 报错
无法校验查询语句权限，请联系管理员，错误信息：line 1 column 75 near "partition(p10)" 

- 错误日志详情
`
[2023-10-13 09:32:07,130][MainThread:139625455327040][task_id:default][query_privileges.py:94][ERROR]- 无法校验查询语句权限，me，select order_no from user_wallet_log partition(p10);，Traceback (most recent call last):
  File "/opt/app/sql/query_privileges.py", line 73, in query_priv_check
    table_ref = _table_ref(sql_content, instance, db_name)
  File "/opt/app/sql/query_privileges.py", line 485, in _table_ref
    query_tree = engine.query_print(
  File "/opt/app/sql/engines/goinception.py", line 186, in query_print
    raise RuntimeError(print_info.get("errmsg"))
RuntimeError: line 1 column 75 near "partition(p10)"
`

**环境**
 - 数据库: [mysql/mariadb]
 - 版本: 5.7.31
 - archery版本: v1.10.0
 - goInception版本:v1.3.0-76-g4082e7a

**参数**
新增了参数enable_partition_table= true 也不行
[inc]
backup_host = "127.0.0.1"
backup_port = 3306
backup_user = "goinception"
backup_password = "TcP0Cp!Wx9NtQsXzY6I1N"

enable_alter_database = false
enable_zero_date = true
enable_nullable = true
enable_drop_table = false
enable_set_engine = true
enable_timestamp_type=true
enable_change_column = true

check_timestamp_count = true
check_table_comment = false
check_column_comment = false

check_float_double = false
check_identifier_upper = false
check_identifier_lower = false
check_read_only = true
enable_partition_table= true

**Comment by zmix999** [comment]
可以看下我fork分支，修复了这个问题https://gitee.com/zhoujin826/goInception
